### ISSUE TITLE
Require repository for hardware-classification-controller under quay.io/metal3-io

### ISSUE THREAD

**Issue by Ashughorla** [metal3-io/hardware-classification-controller#1]
Please create a new repository for hardware-classification-controller under quay.io/metal3-io project, so that we are able to push our image under that.
Till now we are using docker hub repository.
@dhellmann

**Comment by dhellmann** [comment]
In order for the setup to finish successfully there needs to be a Dockerfile in this repository. I don't see any code at all here, yet. Is the development happening in another repository?

**Comment by digambar15** [comment]
We are pushing PR Today with base CRD framework.

**Comment by stbenjam** [comment]
@digambar15 What's the status of this? Could we get the scaffolding at least merged so we can setup the repo?

**Comment by digambar15** [comment]
@stbenjam  Once #PR 2 is merged, we can create query.io/metal3/hardware-classification-controller repo.

**Comment by stbenjam** [comment]
Looks like there's a dockerfile now, can someone create the repo on Quay?


/cc @dhellmann @maelk

**Comment by dhellmann** [comment]
> Looks like there's a dockerfile now, can someone create the repo on Quay?
> 
> /cc @dhellmann @maelk

I've got it.

**Comment by dhellmann** [comment]
Done: https://quay.io/repository/metal3-io/hardware-classification-controller
