### ISSUE TITLE
For a given HardwareClassification profile, Disk parameters (count or size) should be validated and compared independently.

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/hardware-classification-controller#13]
1. Profile is created with either minimumSizeGB and/or maximumsizeGB i.e. only size/s are specified but no disk count is given.
2. This profile when applied should be rejected with proper error message. In another words, with Disk size in picture, Disk count should be made mandatory.

**Comment by maelk** [comment]
I was giving this a though after the meeting, and what kind of behaviour would you expect ? IMHO not giving a disk count should not trigger any error. you would just verify that all the disks are fitting the disk size requirement whatever the number of disks there are. What is the reason for requiring it to fail ?

**Comment by sumitjadhav1** [comment]
Yes @maelk agreed. Actually this issue was raised based on the initial code for comparison and validation.
Updating the title as per internal discussion.

**Comment by nehaalhat** [comment]
This issue is fixed in PR https://github.com/metal3-io/hardware-classification-controller/pull/24

**Comment by sumitjadhav1** [comment]
The issue is fixed & verified. All the validations & comparisons are performed independently. 
Closing it now.
