### ISSUE TITLE
When there are no hosts to compare and validate, proper message should be displayed in logs, like "no hosts found"

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/hardware-classification-controller#16]
When there are no hosts to compare and validate, proper message should be displayed in logs, like "no hosts found"

This case is possible when all the hosts are in states other than "Ready" and we try to apply HardwareClassification profile.

**Comment by nehaalhat** [comment]
This issue is fixed in PR https://github.com/metal3-io/hardware-classification-controller/pull/25

**Comment by sumitjadhav1** [comment]
Issue is resolved & verified. Closing it now.

```
"No BareMetal Host Found" is displayed as INFO in logs.
In the HWCC Status field "No BareMetal Host Found " is displayed in ERROR column.
```
