### ISSUE TITLE
Manual validation should be applied to YAML when any of sub-parameters of supported parameters are not present in YAML.

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/hardware-classification-controller#22]
As of now we have support for following parameters in Hardware classification :
1. CPU 2. DISK 3. RAM 4. NIC

Suppose a profile is configured with combination like : 
1. Configure CPU and all its sub-parameters; Configure RAM/DISK/NIC but without any sub-parameters
2. Configure CPU, RAM and all its sub-parameters; Configure DISK/NIC but without any sub-parameters

We should validate the YAML before applying such profiles and display errors/warnings for appropriate parameters :
1. When all main parameters are present but without any sub-parameters, reject the profile at the entry itself.
2. When some of the parameters are configured properly with their sub-parameters, display warning/s for remaining parameters that they're empty or not provided. Hardware classification should not be affected in this case but warning should be displayed.

**Comment by nehaalhat** [comment]
This issue is fixed in PR https://github.com/metal3-io/hardware-classification-controller/pull/24

**Comment by sumitjadhav1** [comment]
When the parent parameters are specified without its sub-parameters, error "Hardware Profile details cannot be empty " was raised.

Working as expected, marking it as Closed.
