### ISSUE TITLE
Manual validation should be applied when no values are provided in YAML for supported sub-parameters.

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/hardware-classification-controller#23]
As of now we have support for following parameters in Hardware classification :
**1. CPU 2. DISK 3. RAM 4. NIC**

Suppose a profile is configured with combination like :
1. Configure CPU/NIC with its sub-parameters like min/maxCount or min/maxSpeed but no values provided
2. Configure DISK/RAM with their sub-parameters like min/maxSize but no values provided

We should validate the YAML while applying such profiles and display errors for appropriate parameters/sub-parameters.

**Comment by nehaalhat** [comment]
This issue is fixed in PR https://github.com/metal3-io/hardware-classification-controller/pull/24

**Comment by sumitjadhav1** [comment]
If the sub-parameters are left empty, Proper Error Message "Invalid CPU/RAM/NIC/DISK Details" is raised.

Issue is verified, marking Closed.
