### ISSUE TITLE
Provisioned node's labels should not be deleted, if we make changes in the same profile and apply.

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/hardware-classification-controller#36]
Steps to reproduce :
1. Initially have 2-3 BMH in Ready state, create one HCC profile and apply the same.
2. Check that HCC applies label/s to matching host/s as per criteria.
3. Now change state of one of the BMH such that it is in Non-Ready state (E.g. execute provision cluster script so that one BMH changes state from Ready -> Provisioning)
4. Now re-apply the same HCC profile created in Step-1.
5. Check the status of labels applied earlier in Step-2.

Observations : For node/s in Provision-ed/ing state (non-ready state to be specific), earlier applied labels should not be deleted in above scenario.

[provision_node_label_deletion_issue.txt](https://github.com/metal3-io/hardware-classification-controller/files/5082564/provision_node_label_deletion_issue.txt)

<img width="927" alt="provision_delete_label" src="https://user-images.githubusercontent.com/48747693/90366249-b8dcbb80-e084-11ea-818a-2f1104060d62.PNG">

**Comment by sharajat** [comment]
This is fixed.

**Comment by sumitjadhav1** [comment]
Provisioned node's label did not get deleted if we apply the same profile and apply. It will be deleted from non-matched Ready state hosts in new iteration.

Marking it Closed.
