### ISSUE TITLE
Extend the HCC to detect and classify baremetal host for SRIOV/DPDK functions

### ISSUE THREAD

**Issue by sb1975** [metal3-io/hardware-classification-controller#4]
Probably this could be done later once it is clear how SRIOV/DPDK configuration would be done for a host provisioning. But eventually there would be a need for HCC to classify baremetal hosts based on SRIOV/DPDK functions as well please.

**Comment by sb1975** [comment]
This will have dependency on enablement via BMO - Sriov enablement in BMO : https://github.com/metal3-io/baremetal-operator/pull/302

**Comment by digambar15** [comment]
@sb1975  Let's discuss this in details on slack as HCC is getting ready to add such features.

**Comment by maelk** [comment]
It would be good to have a design doc on this with the expected changes on BMH, HWC and on the controllers.

**Comment by digambar15** [comment]
Yes, Will come up wtih design.
