### ISSUE TITLE
Extend the HCC to detect and classify bmh hosts based on extra parameters (Disk and NIC)

### ISSUE THREAD

**Issue by snehal1797** [metal3-io/hardware-classification-controller#53]
HCC validates and classifies the hosts based on user hardware requirements
From the user perspective it will be helpful to classify matched host.
HCC should also compare and classify bare-metal hosts based on extra parameters in CPU ,DISK ,Firmware, NIC and SystemVendor.

**Comment by digambar15** [comment]
Do you mean to add more params in existing resources ?

**Comment by snehal1797** [comment]
> Do you mean to add more params in existing resources ?

At the time of testing HWCC, we found out that we can add more parameters in existing resources so that we can identify matched hosts more precisely.

For example, in Disk supported parameters are only size and count, in addition to these user can identify types of Disk (for eg: HDDs, SSDs, RAID or NVMes). This will help the user for Day-1,Day-2 scenarios.
CPU architecture will be useful if the user wants to have 32-bit or 64-bit processor as per his requirements.
If user is interested in particular NIC vendor, then NIC vendor can be added as parameter.

New parameters such as Firmware and SystemVendor will be added advantage to identify matched hosts.
System Vendor will be useful to add as a new parameter if the user is looking for particular vendor and their hardware for his application to support or deploy on.
Firmware will be useful to add as a new parameter if user is looking for specific feature/s  in particular releases or versions.

**Comment by digambar15** [comment]
Ohh.. I see you suggested changes in the proposal https://github.com/metal3-io/metal3-docs/pull/147
I will hold the PR till the proposal gets merged.

**Comment by snehal1797** [comment]
As the proposal is divided into two parts, we are creating separate issues for two different proposals.

At the time of testing HWCC, we found out that we can add more parameters in existing resources so that we can identify matched hosts more precisely.

For example, in Disk supported parameters are only size and count, in addition to these user can identify types of Disk (for eg: HDDs, SSDs, RAID or NVMes). This will help the user for Day-1,Day-2 scenarios.

If user is interested in particular NIC vendor, then NIC vendor can be added as parameter.

**Comment by Ashughorla** [comment]
Proposal merged [Support for additional parameters Disk and NIC](https://github.com/metal3-io/metal3-docs/blob/master/design/hardware-classification-controller/support-for-new-parameters-hwcc-DiskAndNIC.md)

PRs created : 
Disk : [PR-64](https://github.com/metal3-io/hardware-classification-controller/pulls/64)
NIC : [PR-63](https://github.com/metal3-io/hardware-classification-controller/pulls/63)

**Comment by sumitjadhav1** [comment]
Since this support is now available (all design PRs are merged and verified by QA), this issue can be closed.

/close
