### ISSUE TITLE
Extend the HCC to detect and classify bmh hosts based on extra parameters (CPU, System Vendor and Firmware)

### ISSUE THREAD

**Issue by snehal1797** [metal3-io/hardware-classification-controller#56]
_HCC should also compare and classify bare-metal hosts based on extra parameters in CPU, Firmware and System Vendor._

At the time of testing HWCC, we found out that we can add more parameters in existing resources so that we can identify matched hosts more precisely.

CPU architecture will be useful if the user wants to have 32-bit or 64-bit processor as per his requirements.

New parameters such as Firmware and System Vendor will be added advantage to identify matched hosts.

System Vendor will be useful to add as a new parameter if the user is looking for particular vendor and their hardware for his application to support or deploy on.
Firmware will be useful to add as a new parameter if user is looking for specific feature/s in particular releases or versions.

**Comment by Ashughorla** [comment]
Proposal merged. [Add support for additional parameters](https://github.com/metal3-io/metal3-docs/blob/master/design/hardware-classification-controller/support-for-new-parameters-hwcc.md)

PRs created :
CPU Arch :  [PR-68](https://github.com/metal3-io/hardware-classification-controller/pulls/68)
System Vendor : [PR-65](https://github.com/metal3-io/hardware-classification-controller/pulls/65)
Firmware : [PR-66](https://github.com/metal3-io/hardware-classification-controller/pulls/66)

**Comment by sumitjadhav1** [comment]
Since this support is now available (all design PRs are merged and verified by QA), this issue can be closed.

/close
