### ISSUE TITLE
Upgrade to CRD API to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/hardware-classification-controller#62]
The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition will no not be served anymore starting from K8s v1.22. We should upgrade all our CRDs to v1.

Reference document: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

**Comment by fmuyassarov** [comment]
Was fixed in https://github.com/metal3-io/hardware-classification-controller/pull/67.

**Comment by Ashughorla** [comment]
Changes are done. PR merged.
PR link : [PR-75](https://github.com/metal3-io/hardware-classification-controller/pull/75)

We can close it @fmuyassarov
