### ISSUE TITLE
User provided label values are not updated for matching hosts

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/hardware-classification-controller#72]
User provided label values are not updated for matching BMH, currently only default label value is applied i.e. "matches"

This issue has occurred post refactoring in HWCC.

@poonampawar28

**Comment by jtwill98** [comment]
Did the merge of issue 73 (User defined label value updated) resolve this issue and can this issue be closed?

**Comment by sumitjadhav1** [comment]
Yes, this has been verified with fix of PR#73. Closing the issue as custom labels are getting applied properly now.
