### ISSUE TITLE
Error should be updated to "No BareMetalHost Found" in HCC status when there are no baremetal hosts

### ISSUE THREAD

**Issue by Himani-Raina** [metal3-io/hardware-classification-controller#79]
When there are no BareMetalHosts in BMH list, we applied the profile as below, status column for the profile is updated to "unmatched" instead of that, it should be updated as "**No BareMetalHost Found**" in error column

```apiVersion: metal3.io/v1alpha1
kind: HardwareClassification
metadata:
  name: hardwareclassification-sample
  namespace: metal3
  labels:
    hardwareclassification-sample: matches
spec:
  hardwareCharacteristics:
      cpu:
         architecture : "x86_64"
         minimumCount: 48
         maximumCount: 72
         minimumSpeedMHz: 1000
         maximumSpeedMHz: 3600
      disk:
         minimumCount: 1
         maximumCount: 8

**Comment by Ashughorla** [comment]
Changes are merged in Master branch.
PR link: [PR-82](https://github.com/metal3-io/hardware-classification-controller/pull/82)

We can close it @Himani-Raina
