### ISSUE TITLE
Update error count in hwcc status field 

### ISSUE THREAD

**Issue by Dimple-dsk** [metal3-io/hardware-classification-controller#80]
Hardware-classification-controller should update count of error host such as registration error, provisioning error, power management error, inspection error in the hwcc status field and also label error hosts accordingly.

As of now hcc only updates the profile match status and the error state, it should also update the count for the error host as well.

**Comment by jtwill98** [comment]
Agree, the work done for Airship with regards to count of errors should be exposed for consumption by the Metal3 community.

**Comment by Ashughorla** [comment]
PR is raised [PR-89](https://github.com/metal3-io/hardware-classification-controller/pull/89)

Kindly review.

**Comment by Rozzii** [comment]
Is this issue still alive or can we close this ? 
/cc @sumitjadhav1
/cc @Ashughorla
