### ISSUE TITLE
bash: hack/tools/bin/kustomize: No such file or directory . error: no objects passed to apply

### ISSUE THREAD

**Issue by poonampawar28** [metal3-io/hardware-classification-controller#84]
While installing CRDs by using make install got error "bash: hack/tools/bin/kustomize: No such file or directory
error: no objects passed to apply" 
![kustomize](https://user-images.githubusercontent.com/69086580/137844220-de18a427-c679-453b-b4bb-3e4b3b7d485c.png)

**Comment by Ashughorla** [comment]
PR in review.
PR link [PR-85](https://github.com/metal3-io/hardware-classification-controller/pull/85)
